- name: set swap_file variable
  set_fact:
    swap_file: /var/cache/swap/swapfile.swap

- name: create swap directory
  file:
    path: /var/cache/swap
    state: directory
    mode: 0755

- name: check if swap file exists
  stat:
    path: "{{ swap_file }}"
  register: swap_file_check

- name: create swap file
  command: fallocate -l 10MB {{ swap_file }}
  when: not swap_file_check.stat.exists

- name: Create swap space
  command: dd if=/dev/zero of={{ swap_file }} bs=1k count=2M
  when: not swap_file_check.stat.exists

- name: set permissions on swap file
  file:
    path: "{{ swap_file }}"
    mode: 0600

- name: format swap file
  command: mkswap {{ swap_file }}
  when: not swap_file_check.stat.exists

- name: add to fstab
  lineinfile:
    dest: /etc/fstab
    regexp: "{{ swap_file }}"
    line: "{{ swap_file }} none swap sw 0 0"

- name: turn on swap
  command: swapon -av
  when: ansible_swaptotal_mb < 1

- name: set swapiness
  sysctl:
    name: vm.swappiness
    value: "1"